apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nada-datasetenricher-alert
  namespace: nada
  labels:
    team: nada
spec:
  groups:
  - name: nada-datasetenricher-alert
    rules:
    - alert: InstanceDown
      expr: kube_job_failed{job_name=~"^nada-datasetenricher.*", namespace="nada"} > 0
      for: 2m
      annotations:
        consequence: Synkronisering av metadata om datasett i markedsplassen med BigQuery er stoppet
        action: "`Se logger på https://logs.adeo.no -> søk etter `pod:nada-datasetenricher* AND namespace:nada`"
        summary: |-
          Naisjob nada-datasetenricher feiler i prod-gcp namespace nada (repo https://github.com/navikt/nada-datasetenricher)
      labels:
        namespace: nada
        severity: critical
