apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: nada
  name: nada-datasetenricher
  namespace: nada
spec:
  image: {{ image }}
  ttlSecondsAfterFinished: 340
  backoffLimit: 2
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  schedule: '0 * * * *'
  accessPolicy:
    outbound:
      rules:
        - application: nada-backend
